// Generated by CoffeeScript 1.6.3
(function() {
  var app, express, http, path, routes, user;

  express = require('express');

  routes = require('./routes');

  user = require('./routes/user');

  http = require('http');

  path = require('path');

  app = express();

  app.set('layout', 'layout');

  app.set('partials', {
    head: 'partials/head',
    navbar: 'partials/navbar'
  });

  app.engine('html', require('hogan-express'));

  app.enable('view cache');

  app.configure(function() {
    app.set('port', process.env.PORT || 3000);
    app.set('views', __dirname + '/views');
    app.set('view engine', 'html');
    app.use(express.favicon());
    app.use(express.logger('dev'));
    app.use(express.json());
    app.use(express.urlencoded());
    app.use(express.methodOverride());
    app.use(express.cookieParser('your secret here'));
    app.use(express.session());
    app.use(app.router);
    app.use(express["static"](path.join(__dirname, 'public')));
    return app.use(express["static"](path.join(__dirname, 'bower_components')));
  });

  app.configure('development', function() {
    return app.use(express.errorHandler());
  });

  app.get('/', routes.index);

  app.get('/users', user.list);

  http.createServer(app).listen(app.get('port'), function() {
    return console.log('Express server listening on port ' + app.get('port'));
  });

}).call(this);

/*
//@ sourceMappingURL=app.map
*/
